name: example
description: Gernerate model class from Json files.
version: 0.0.1
author: wendux <824783146@qq.com>
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.5.1

  json_model:
    path: ../
